name: First workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
    
jobs:
  RestAssured_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('RestAssured/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: restassured-test-reports
        path: RestAssured/target/site
      
    

    
